site_name: Scot's GitHub Site on MkDocs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: dark
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Light Mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to Light Mode
      primary: teal
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scotpatti
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/scot-anderson-37059794/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tasklist
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright:
  Copyright &copy; 2025 <a href="https://github.com/scotpatti" target="_blank" rel="noopener">Scot Anderson</a>